package com.picfix.tools.bean

enum class FileStatus {
    COPY, UNZIP_BACKUP, UNZIP_WX, DECODE_MESSAGE, DECODE_ACCOUNT, DECODE_CONTACT, ANALYZE, ZIP, PIC, VIDEO, VOICE, DOC, DELETE, SEARCH, SAVE, FILE
}