package com.picfix.tools.utils

import android.util.ArrayMap

object Dict {

    fun getPhoneModel(): ArrayMap<String, String> {
        val map = ArrayMap<String, String>()
        map.put("1", "魅族 17")
        map.put("2", "魅族 17 Pro")
        map.put("3", "魅族 16")
        map.put("4", "魅族 16 Xs")
        map.put("5", "魅族 16T")
        map.put("6", "魅族 16s")
        map.put("7", "魅族 16s Pro")
        map.put("8", "魅族 Note9")
        map.put("9", "魅族 Note8")
        map.put("10", "魅族 X8")
        map.put("11", "魅族 V8")
        map.put("12", "魅族 Note7")
        map.put("13", "魅族 Note6")
        map.put("14", "魅族 Note5")
        map.put("15", "魅族 Note4")
        map.put("16", "魅蓝 E3")
        map.put("17", "魅蓝 S6")
        map.put("18", "魅蓝 E2")
        map.put("19", "魅蓝 X")
        map.put("20", "魅蓝 5S")
        map.put("21", "OPPO Find X3")
        map.put("22", "OPPO K7")
        map.put("23", "OPPO Reno4")
        map.put("24", "OPPO Reno5")
        map.put("25", "OPPO Reno5 Pro")
        map.put("26", "OPPO Reno5 Pro+")
        map.put("27", "OPPO R1")
        map.put("28", "OPPO R2")
        map.put("29", "OPPO R3")
        map.put("30", "OPPO R4")
        map.put("31", "OPPO R5")
        map.put("32", "OPPO R6")
        map.put("33", "OPPO R7")
        map.put("34", "OPPO R9")
        map.put("35", "OPPO R9s")
        map.put("36", "OPPO R11")
        map.put("37", "OPPO R11 Plus")
        map.put("38", "OPPO R7 plus")
        map.put("39", "OPPO R9 plus")
        map.put("40", "OPPO A11")
        map.put("41", "OPPO A33")
        map.put("42", "OPPO A37")
        map.put("43", "OPPO A41")
        map.put("44", "OPPO A61s")
        map.put("45", "OPPO A53")
        map.put("46", "OPPO A59")
        map.put("47", "OPPO A59s")
        map.put("48", "OPPO A57s")
        map.put("49", "OPPO A77")
        map.put("50", "OPPO A93")
        map.put("51", "Xiaomi 2")
        map.put("52", "Xiaomi 2A")
        map.put("53", "Xiaomi 2S")
        map.put("54", "Xiaomi 3")
        map.put("55", "Xiaomi 4")
        map.put("56", "Xiaomi 4C")
        map.put("57", "Xiaomi 4S")
        map.put("58", "Xiaomi Note")
        map.put("59", "Xiaomi Pro")
        map.put("60", "Xiaomi 5")
        map.put("61", "Xiaomi 5s")
        map.put("62", "Xiaomi 5s Plus")
        map.put("63", "Xiaomi Note2")
        map.put("64", "Xiaomi mix")
        map.put("65", "Xiaomi 6")
        map.put("66", "Xiaomi 6s")
        map.put("67", "Xiaomi 10")
        map.put("68", "Xiaomi 10青春版")
        map.put("69", "Xiaomi 11")
        map.put("70", "Redmi 10X")
        map.put("71", "Redmi 10X Pro")
        map.put("72", "Redmi Note 9")
        map.put("73", "Redmi Note 9 Pro")
        map.put("74", "Redmi Note 8")
        map.put("75", "Redmi Note 8 Pro")
        map.put("76", "Redmi 9")
        map.put("77", "Redmi 9A")
        map.put("78", "Redmi 8")
        map.put("79", "Redmi 8A")
        map.put("80", "Redmi K30")
        map.put("81", "Redmi K30S")
        map.put("82", "Redmi 7")
        map.put("83", "Redmi 6 Pro")
        map.put("84", "Redmi 6A")
        map.put("85", "Redmi 6")
        map.put("86", "Redmi 5")
        map.put("87", "Redmi 5 Plus")
        map.put("88", "Redmi 5A")
        map.put("89", "Redmi 4X")
        map.put("90", "Redmi 4")
        map.put("91", "Redmi 4A")
        map.put("92", "Redmi 3X")
        map.put("93", "Redmi 3S")
        map.put("94", "HUAWEI Mate7")
        map.put("95", "HUAWEI Mate8")
        map.put("96", "HUAWEI Mate9")
        map.put("97", "HUAWEI Mate10")
        map.put("98", "HUAWEI Mate20")
        map.put("99", "HUAWEI Mate9 PLUS")
        map.put("100", "HUAWEI P8")
        map.put("101", "HUAWEI P9")
        map.put("102", "HUAWEI P10")
        map.put("103", "HUAWEI P9 PLUS")
        map.put("104", "HUAWEI P10 PLUS")
        map.put("105", "HUAWEI P8lite")
        map.put("106", "HUAWEI V9")
        map.put("107", "HUAWEI 畅玩4")
        map.put("108", "HUAWEI 畅玩4C")
        map.put("109", "HUAWEI 畅玩4X")
        map.put("110", "HUAWEI 畅玩5")
        map.put("111", "HUAWEI 畅玩5A")
        map.put("112", "HUAWEI 畅玩6A")
        map.put("113", "HUAWEI 畅享5S")
        map.put("114", "HUAWEI 畅享6S")
        map.put("115", "HUAWEI 畅享7")
        map.put("116", "HUAWEI 畅享7PLUS")
        map.put("117", "HUAWEI Nova2")
        map.put("118", "HUAWEI Nova2 PLUS")
        map.put("119", "HUAWEI 麦芒4")
        map.put("120", "HUAWEI 麦芒5")
        map.put("121", "荣耀3C")
        map.put("122", "荣耀4A")
        map.put("123", "荣耀4X")
        map.put("124", "荣耀5")
        map.put("125", "荣耀5X")
        map.put("126", "荣耀6")
        map.put("127", "荣耀6PLUS")
        map.put("128", "荣耀7")
        map.put("129", "荣耀7I")
        map.put("130", "荣耀8")
        map.put("131", "荣耀8青春版")
        map.put("132", "荣耀NOTE8")

        return map
    }


    fun getHUAWEIName(key: String): String? {
        val map = ArrayMap<String, String>()
        map.put("ELE-AL00", "HUAWEI P30")
        map.put("VOG-AL10", "HUAWEI P30 Pro")
        map.put("EML-AL00", "HUAWEI P20")
        map.put("CLT-AL00", "HUAWEI P20 Pro")
        map.put("ALP-AL00", "HUAWEI Mate10")
        map.put("BLA-AL00", "HUAWEI Mate10 Pro")
        map.put("BLA-AL00P", "HUAWEI Mate10 保时捷版")
        map.put("HMA-AL00", "HUAWEI Mate20")
        map.put("LYA-AL00", "HUAWEI Mate20 Pro")
        map.put("LYA-AL00P", "HUAWEI Mate20 保时捷版")
        map.put("TAS-AN00", "HUAWEI Mate30")
        map.put("TAS-AL00", "HUAWEI Mate30")
        map.put("LIO-AN00", "HUAWEI Mate30 Pro")
        map.put("LIO-AN00P", "HUAWEI Mate30 保时捷版")
        map.put("NOH-AN00", "HUAWEI Mate40")
        map.put("NOP-AN00", "HUAWEI Mate40 Pro")
        map.put("NOP-AL00", "HUAWEI Mate40 保时捷版")
        map.put("VOG-AL00", "HUAWEI P30 Pro")
        map.put("SEA-AL10", "HUAWEI Nova5 Pro")
        map.put("VCE-AL00", "HUAWEI Nova 4")
        map.put("PAR-AL00", "HUAWEI Nova 3")
        map.put("RIO-UL00", "HUAWEI G7Plus")
        map.put("VNS-DL00", "HUAWEI G9青春版")
        map.put("VNS-AL00", "HUAWEI G9青春版")
        map.put("MT7-TL10", "HUAWEI Mate7")
        map.put("MT7-CL00", "HUAWEI Mate7")
        map.put("MT7-AL00", "HUAWEI Mate7")
        map.put("NXT-TL00", "HUAWEI Mate8")
        map.put("NXT-QL10", "HUAWEI Mate8")
        map.put("MHA-AL00", "HUAWEI Mate9")
        map.put("CRR-CL00", "HUAWEI Mates")
        map.put("CRR-UL00", "HUAWEI Mates")
        map.put("CRR-TL00", "HUAWEI Mates")
        map.put("VTR-AL00", "HUAWEI P10")
        map.put("VKY-AL00", "HUAWEI P10 PLUS")
        map.put("GRA-UL10", "HUAWEI P8")
        map.put("ALE-TL00", "HUAWEI P8lite")
        map.put("EVA-AL10", "HUAWEI P9")
        map.put("VIE-AL10", "HUAWEI P9 PLUS")
        map.put("UK-AL20", "HUAWEI V9D")
        map.put("PIC-AL00", "HUAWEI Nova2")
        map.put("BAC-AL00", "HUAWEI Nova2 PLUS")
        map.put("CHM-TL00H", "HUAWEI 畅玩 4C")
        map.put("CHM-CL00", "HUAWEI 畅玩 4C")
        map.put("CHE2-UL00", "HUAWEI 畅玩 4X")
        map.put("CHE1-CL20", "HUAWEI 畅玩 4X")
        map.put("CUN-AL00", "HUAWEI 畅玩 5")
        map.put("CAM-AL00", "HUAWEI 畅玩 5A")
        map.put("DLI-AL10", "HUAWEI 畅玩 6A")
        map.put("BLN-AL40", "HUAWEI 畅玩 6X")
        map.put("TAG-AL00", "HUAWEI 畅享 5S")
        map.put("TAG-UL00", "HUAWEI 畅享 5S")
        map.put("TAG-TL00", "HUAWEI 畅享 5S")
        map.put("NCE-AL00", "HUAWEI 畅享 6")
        map.put("NCE-AL10", "HUAWEI 畅享 6")
        map.put("DIG-TL10", "HUAWEI 畅享 6S")
        map.put("DIG-AL00", "HUAWEI 畅享 6S")
        map.put("SLA-AL00", "HUAWEI 畅享 7")
        map.put("TRT-AL10", "HUAWEI 畅享 7 PLUS")
        map.put("ART-AL00X", "HUAWEI 畅享 10")
        map.put("ART-AL00M", "HUAWEI 畅享 10")
        map.put("RIO-AL00", "HUAWEI 麦芒 4")
        map.put("MLA-TL00", "HUAWEI 麦芒 5")
        map.put("MLA-AL10", "HUAWEI 麦芒 5")
        map.put("H30-T00", "荣耀 3C")
        map.put("SCL-TL00", "荣耀 4A")
        map.put("SCL-AL00", "荣耀 4A")
        map.put("SCL-CL00", "荣耀 4A")
        map.put("CHE-TL00H", "荣耀 4X")
        map.put("CUN-AL00", "荣耀 5")
        map.put("KIW-AL10", "荣耀 5X")
        map.put("KIW-UL00", "荣耀 5X")
        map.put("KIW-AL20", "荣耀 5X")
        map.put("H60-L03", "荣耀 6")
        map.put("PE-TL00M", "荣耀 6 Plus")
        map.put("PE-TL20", "荣耀 6 Plus")
        map.put("PLK-AL10", "荣耀 7")
        map.put("ATH-AL00", "荣耀 7I")
        map.put("FRD-AL00", "荣耀 8")
        map.put("PRA-AL00X", "荣耀 8 青春版")
        map.put("EDI-AL10", "荣耀 NOTE8")
        map.put("KNT-AL20", "荣耀 V8")
        map.put("COL-AL10", "荣耀 10")
        map.put("BKL-AL20", "荣耀 V10")
        map.put("PCT-AL10", "荣耀 V20")
        map.put("OXF-AN10", "荣耀 V30 PRO")
        map.put("WLZ-AL10", "HUAWEI Nova6")

        return map[key]
    }

    fun getRecommendList(): ArrayList<String> {
        val list = arrayListOf<String>()
        list.add("软件成功恢复了我的重要文件,可以自己操作，不用去店里维修,不用担心信息泄露的问题！")
        list.add("挺不错的，之前删除了一个微信好友，别的方法都没找回来，是强力恢复帮我找回来了。")
        list.add("这个软件操作也挺简单的，手机直接下载应用，根据提示扫描恢复就行了。")
        list.add("女儿失手给我把一些重要的微信聊天记录和图片删了，还好找了回来，还是得感谢软件为我找回那些重要数据！")
        list.add("2年前删除的好友竟然都找回来了，太开心了( •̀ ω •́ )y")
        list.add("还不错，至少是安全的，没有影响到我的微信")
        list.add("哈哈哈，表情包都找出来了，真的方便")
        list.add("账单恢复那个恢复出了以前删除掉的转账记录，太棒了")
        list.add("不知道恢复出厂设置以后能不能恢复，还没试")
        list.add("恢复出的聊天记录还有待整理优化，其它还好")
        list.add("换新手机了，想把旧手机数据彻底清理掉，一键删除功能还是挺好用的。")
        return list
    }
}